version: "3"

services: 
  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - /home/fali/projects/docker/datak/nginx.conf:/etc/nginx/nginx.conf
      - /home/fali/projects/docker/datak/nginx:/etc/nginx/sites-enabled
      - /home/fali/projects/docker/datak/website:/var/www/html
      - /home/fali/projects/docker/datak/logs/nginx:/var/log/nginx
    ports:
      - "80:80"
      - "443:443"
    networks:
      - datak
    restart: always

networks:
  datak:
    external: true