version: "3"

services:
  app:
    container_name: php-fpm
    restart: always
    build:
      context: ./php-fpm
      args:
        - INSTALL_GD=${PHP_FPM_INSTALL_GD}
        - INSTALL_COMPRESSION=${PHP_FPM_INSTALL_COMPRESSION}
        - INSTALL_FTP=${PHP_FPM_INSTALL_FTP}
        - INSTALL_MBSTRING=${PHP_FPM_INSTALL_MBSTRING}
        - INSTALL_MCRYPT=${PHP_FPM_INSTALL_MCRYPT}
        - INSTALL_PDO_MYSQL=${PHP_FPM_INSTALL_PDO_MYSQL}
        - INSTALL_PDO_POSTGRESQL=${PHP_FPM_INSTALL_PDO_POSTGRESQL}
        - INSTALL_MYSQLI=${PHP_FPM_INSTALL_MYSQLI}
        - INSTALL_BCMATH=${PHP_FPM_INSTALL_BCMATH}
        - INSTALL_OPCACHE=${PHP_FPM_INSTALL_OPCACHE}
        - INSTALL_INTL=${PHP_FPM_INSTALL_INTL}
        - INSTALL_XDEBUG=${PHP_FPM_INSTALL_XDEBUG}
        - INSTALL_TOKENIZER=${PHP_FPM_INSTALL_TOKENIZER}
        - INSTALL_JSON_XML=${PHP_FPM_INSTALL_JSON_XML}
        - INSTALL_CURL=${PHP_FPM_INSTALL_CURL}
        - INSTALL_OPENSSL=${PHP_FPM_INSTALL_OPENSSL}
        - INSTALL_COMPOSER=${PHP_FPM_INSTALL_COMPOSER}
      dockerfile: Dockerfile
    expose:
      - "9000"    
    volumes:
      - ${APPLICATION}:/var/www/html
    networks:
      - datak

  
  myqsl:
    image: mysql:latest
    container_name: myqsl
    ports:
      - "3306:3306"
    restart: on-failure
    networks:
      - database
      - datak
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=site
      - MYSQL_USER=user
      - MYSQL_PASSWORD=userpass
    volumes:
      - /home/fali/projects/docker/datak/database_backup:/var/lib/mysql
    
  phpmyadmin:
    depends_on:
      - myqsl
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    ports:
      - "8089:80"
    environment:
      PMA_HOST: myqsl
      MYSQL_ROOT_PASSWORD: password 
    networks:
      - database

networks:
  database:
  datak:
    external: true